def test_failure():
    # disabled
    return True
    raise Exception("This test failed")
