def test_failure():
    raise Exception("This test failed")
